[package]
name = "parachain-template-node"
description = "A parachain node template built with Substrate and Cumulus, part of Polkadot Sdk. (polkadot v1.12.0)"
version = "0.1.0"
license = "MIT-0"
authors.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true
publish = false
build = "build.rs"

# [[bin]]
# name = "parachain-template-node"

[dependencies]
clap = { version = "4.5.3", features = ["derive"] }
log = { workspace = true, default-features = true }
codec = { package = "parity-scale-codec", version = "3.0.0" }
serde = { features = ["derive"], workspace = true, default-features = true }
jsonrpsee = { version = "0.22", features = ["server"] }
futures = "0.3.28"
serde_json = { workspace = true, default-features = true }
docify = "0.2.8"
parachain-template-runtime = { version = "0.1.0", path = "../runtime" }
frame-benchmarking = { version = "34.0.0", path = "../../../substrate/frame/benchmarking" }
frame-benchmarking-cli = { version = "38.0.0", path = "../../../substrate/utils/frame/benchmarking-cli" }
pallet-transaction-payment-rpc = { version = "36.0.0", path = "../../../substrate/frame/transaction-payment/rpc" }
sc-basic-authorship = { version = "0.40.0", path = "../../../substrate/client/basic-authorship" }
sc-chain-spec = { version = "33.0.0", path = "../../../substrate/client/chain-spec" }
sc-cli = { version = "0.42.0", path = "../../../substrate/client/cli" }
sc-client-api = { version = "34.0.0", path = "../../../substrate/client/api" }
sc-offchain = { version = "35.0.0", path = "../../../substrate/client/offchain" }
sc-consensus = { version = "0.39.1", path = "../../../substrate/client/consensus/common" }
sc-executor = { version = "0.38.0", path = "../../../substrate/client/executor" }
sc-network = { version = "0.40.0", path = "../../../substrate/client/network" }
sc-network-sync = { version = "0.39.0", path = "../../../substrate/client/network/sync" }
sc-rpc = { version = "35.0.0", path = "../../../substrate/client/rpc" }
sc-service = { version = "0.41.0", path = "../../../substrate/client/service" }
sc-sysinfo = { version = "33.0.0", path = "../../../substrate/client/sysinfo" }
sc-telemetry = { version = "20.0.0", path = "../../../substrate/client/telemetry" }
sc-tracing = { version = "34.0.0", path = "../../../substrate/client/tracing" }
sc-transaction-pool = { version = "34.0.0", path = "../../../substrate/client/transaction-pool" }
sc-transaction-pool-api = { version = "34.0.0", path = "../../../substrate/client/transaction-pool/api" }
sp-api = { version = "32.0.0", path = "../../../substrate/primitives/api" }
sp-block-builder = { version = "32.0.0", path = "../../../substrate/primitives/block-builder" }
sp-blockchain = { version = "34.0.0", path = "../../../substrate/primitives/blockchain" }
sp-consensus-aura = { version = "0.38.0", path = "../../../substrate/primitives/consensus/aura" }
sp-core = { version = "33.0.1", path = "../../../substrate/primitives/core" }
sp-keystore = { version = "0.39.0", path = "../../../substrate/primitives/keystore" }
sp-io = { version = "36.0.0", path = "../../../substrate/primitives/io" }
sp-runtime = { version = "37.0.0", path = "../../../substrate/primitives/runtime" }
sp-timestamp = { version = "32.0.0", path = "../../../substrate/primitives/timestamp" }
substrate-frame-rpc-system = { version = "34.0.0", path = "../../../substrate/utils/frame/rpc/system" }
substrate-prometheus-endpoint = { version = "0.17.0", path = "../../../substrate/utils/prometheus" }

# Polkadot
polkadot-cli = { path = "../../../polkadot/cli", features = ["rococo-native"], version = "13.0.0" }
polkadot-primitives = { version = "13.0.0", path = "../../../polkadot/primitives" }
xcm = { package = "staging-xcm", path = "../../../polkadot/xcm", default-features = false, version = "13.0.1" }
cumulus-client-cli = { version = "0.13.0", path = "../../../cumulus/client/cli" }
cumulus-client-collator = { version = "0.13.0", path = "../../../cumulus/client/collator" }
cumulus-client-consensus-aura = { version = "0.13.0", path = "../../../cumulus/client/consensus/aura" }
cumulus-client-consensus-common = { version = "0.13.0", path = "../../../cumulus/client/consensus/common" }
cumulus-client-consensus-proposer = { version = "0.13.0", path = "../../../cumulus/client/consensus/proposer" }
cumulus-client-service = { version = "0.13.0", path = "../../../cumulus/client/service" }
cumulus-primitives-core = { version = "0.13.0", path = "../../../cumulus/primitives/core" }
cumulus-primitives-parachain-inherent = { version = "0.13.0", path = "../../../cumulus/primitives/parachain-inherent" }
cumulus-relay-chain-interface = { version = "0.13.0", path = "../../../cumulus/client/relay-chain-interface" }
color-print = "0.3.4"

[build-dependencies]
substrate-build-script-utils = { version = "11.0.0", path = "../../../substrate/utils/build-script-utils" }

[features]
default = []
runtime-benchmarks = [
	"cumulus-primitives-core/runtime-benchmarks",
	"frame-benchmarking-cli/runtime-benchmarks",
	"frame-benchmarking/runtime-benchmarks",
	"parachain-template-runtime/runtime-benchmarks",
	"polkadot-cli/runtime-benchmarks",
	"polkadot-primitives/runtime-benchmarks",
	"sc-service/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
]
try-runtime = [
	"parachain-template-runtime/try-runtime",
	"polkadot-cli/try-runtime",
	"sp-runtime/try-runtime",
]
