[package]
name = "minimal-template-node"
description = "A miniaml Substrate-based Substrate node, ready for hacking. (polkadot v1.9.0)"
version = "0.1.0"
license = "MIT-0"
authors.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true
publish = false
build = "build.rs"

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
clap = { version = "4.5.1", features = ["derive"] }
futures = { version = "0.3.21", features = ["thread-pool"] }
futures-timer = "3.0.1"
jsonrpsee = { version = "0.22", features = ["server"] }
serde_json = { workspace = true, default-features = true }
sc-cli = { version = "0.39.0", path = "../../../substrate/client/cli" }
sc-executor = { version = "0.35.0", path = "../../../substrate/client/executor" }
sc-network = { version = "0.37.0", path = "../../../substrate/client/network" }
sc-service = { version = "0.38.0", path = "../../../substrate/client/service" }
sc-telemetry = { version = "17.0.0", path = "../../../substrate/client/telemetry" }
sc-transaction-pool = { version = "31.0.0", path = "../../../substrate/client/transaction-pool" }
sc-transaction-pool-api = { version = "31.0.0", path = "../../../substrate/client/transaction-pool/api" }
sc-consensus = { version = "0.36.0", path = "../../../substrate/client/consensus/common" }
sc-consensus-manual-seal = { version = "0.38.0", path = "../../../substrate/client/consensus/manual-seal" }
sc-rpc-api = { version = "0.36.0", path = "../../../substrate/client/rpc-api" }
sc-basic-authorship = { version = "0.37.0", path = "../../../substrate/client/basic-authorship" }
sc-offchain = { version = "32.0.0", path = "../../../substrate/client/offchain" }
sc-client-api = { version = "31.0.0", path = "../../../substrate/client/api" }
sp-timestamp = { version = "29.0.0", path = "../../../substrate/primitives/timestamp" }
sp-keyring = { version = "34.0.0", path = "../../../substrate/primitives/keyring" }
sp-api = { version = "29.0.0", path = "../../../substrate/primitives/api" }
sp-blockchain = { version = "31.0.0", path = "../../../substrate/primitives/blockchain" }
sp-block-builder = { version = "29.0.0", path = "../../../substrate/primitives/block-builder" }
sp-io = { version = "33.0.0", path = "../../../substrate/primitives/io" }
sp-runtime = { version = "34.0.0", path = "../../../substrate/primitives/runtime" }
substrate-frame-rpc-system = { version = "31.0.0", path = "../../../substrate/utils/frame/rpc/system" }

# Once the native runtime is gone, there should be little to no dependency on FRAME here, and
# certainly no dependency on the runtime.
polkadot-sdk-frame = { package = "frame", path = "../../../substrate/frame", features = ["experimental", "runtime"], version = "0.1.0" }
runtime = { package = "minimal-template-runtime", path = "../runtime", version = "0.1.0" }

[build-dependencies]
substrate-build-script-utils = { version = "11.0.0", path = "../../../substrate/utils/build-script-utils" }

[features]
default = []
