[package]
name = "solochain-template-node"
description = "A solochain node template built with Substrate, part of Polkadot Sdk. (polkadot v1.12.0)"
version = "0.1.0"
license = "MIT-0"
authors.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true
publish = false

build = "build.rs"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
clap = { version = "4.5.3", features = ["derive"] }
futures = { version = "0.3.30", features = ["thread-pool"] }
serde_json = { workspace = true, default-features = true }
jsonrpsee = { version = "0.22", features = ["server"] }
sc-cli = { version = "0.42.0", path = "../../../substrate/client/cli" }
sp-core = { version = "33.0.1", path = "../../../substrate/primitives/core" }
sc-executor = { version = "0.38.0", path = "../../../substrate/client/executor" }
sc-network = { version = "0.40.0", path = "../../../substrate/client/network" }
sc-service = { version = "0.41.0", path = "../../../substrate/client/service" }
sc-telemetry = { version = "20.0.0", path = "../../../substrate/client/telemetry" }
sc-transaction-pool = { version = "34.0.0", path = "../../../substrate/client/transaction-pool" }
sc-transaction-pool-api = { version = "34.0.0", path = "../../../substrate/client/transaction-pool/api" }
sc-offchain = { version = "35.0.0", path = "../../../substrate/client/offchain" }
sc-consensus-aura = { version = "0.40.0", path = "../../../substrate/client/consensus/aura" }
sp-consensus-aura = { version = "0.38.0", path = "../../../substrate/primitives/consensus/aura" }
sc-consensus = { version = "0.39.1", path = "../../../substrate/client/consensus/common" }
sc-consensus-grandpa = { version = "0.25.0", path = "../../../substrate/client/consensus/grandpa" }
sp-consensus-grandpa = { version = "19.0.0", path = "../../../substrate/primitives/consensus/grandpa" }
sc-client-api = { version = "34.0.0", path = "../../../substrate/client/api" }
sc-rpc-api = { version = "0.39.0", path = "../../../substrate/client/rpc-api" }
sc-basic-authorship = { version = "0.40.0", path = "../../../substrate/client/basic-authorship" }
sp-runtime = { version = "37.0.0", path = "../../../substrate/primitives/runtime" }
sp-io = { version = "36.0.0", path = "../../../substrate/primitives/io" }
sp-timestamp = { version = "32.0.0", path = "../../../substrate/primitives/timestamp" }
sp-inherents = { version = "32.0.0", path = "../../../substrate/primitives/inherents" }
sp-keyring = { version = "37.0.0", path = "../../../substrate/primitives/keyring" }
sp-api = { version = "32.0.0", path = "../../../substrate/primitives/api" }
sp-blockchain = { version = "34.0.0", path = "../../../substrate/primitives/blockchain" }
sp-block-builder = { version = "32.0.0", path = "../../../substrate/primitives/block-builder" }
frame-system = { version = "34.0.0", path = "../../../substrate/frame/system" }
pallet-transaction-payment = { path = "../../../substrate/frame/transaction-payment", default-features = false, version = "34.0.0" }
pallet-transaction-payment-rpc = { version = "36.0.0", path = "../../../substrate/frame/transaction-payment/rpc" }
substrate-frame-rpc-system = { version = "34.0.0", path = "../../../substrate/utils/frame/rpc/system" }
frame-benchmarking-cli = { version = "38.0.0", path = "../../../substrate/utils/frame/benchmarking-cli" }
solochain-template-runtime = { version = "0.1.0", path = "../runtime" }

[build-dependencies]
substrate-build-script-utils = { version = "11.0.0", path = "../../../substrate/utils/build-script-utils" }

[features]
default = []
# Dependencies that are only required if runtime benchmarking should be build.
runtime-benchmarks = [
	"frame-benchmarking-cli/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"sc-service/runtime-benchmarks",
	"solochain-template-runtime/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
]
# Enable features that allow the runtime to be tried and debugged. Name might be subject to change
# in the near future.
try-runtime = [
	"frame-system/try-runtime",
	"pallet-transaction-payment/try-runtime",
	"solochain-template-runtime/try-runtime",
	"sp-runtime/try-runtime",
]
