[package]
name = "minimal-template"
description = "A minimal template built with Substrate, part of Polkadot Sdk. (polkadot v1.12.0)"
version = "0.1.0"
license = "MIT-0"
authors.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true
publish = false

[dependencies]
minimal-template-node = { version = "0.1.0", path = "node" }
minimal-template-runtime = { version = "0.1.0", path = "runtime" }
pallet-minimal-template = { version = "0.1.0", path = "pallets/template" }
polkadot-sdk-docs = { version = "0.1.0", path = "../../docs/sdk" }

frame = { package = "polkadot-sdk-frame", path = "../../substrate/frame", version = "0.3.0" }

# How we build docs in rust-docs
simple-mermaid = "0.1.1"
docify = "0.2.7"
