[package]
name = "solochain-template-runtime"
description = "A solochain runtime template built with Substrate, part of Polkadot Sdk. (polkadot v1.12.0)"
version = "0.1.0"
license = "MIT-0"
authors.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true
publish = false

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "3.6.1", default-features = false, features = [
	"derive",
] }
scale-info = { version = "2.11.1", default-features = false, features = [
	"derive",
	"serde",
] }

# frame
frame-support = { path = "../../../substrate/frame/support", default-features = false, features = ["experimental"], version = "34.0.0" }
frame-system = { path = "../../../substrate/frame/system", default-features = false, version = "34.0.0" }
frame-try-runtime = { path = "../../../substrate/frame/try-runtime", default-features = false, optional = true, version = "0.40.0" }
frame-executive = { path = "../../../substrate/frame/executive", default-features = false, version = "34.0.0" }

# frame pallets
pallet-aura = { path = "../../../substrate/frame/aura", default-features = false, version = "33.0.0" }
pallet-balances = { path = "../../../substrate/frame/balances", default-features = false, version = "35.0.0" }
pallet-grandpa = { path = "../../../substrate/frame/grandpa", default-features = false, version = "34.0.0" }
pallet-sudo = { path = "../../../substrate/frame/sudo", default-features = false, version = "34.0.0" }
pallet-timestamp = { path = "../../../substrate/frame/timestamp", default-features = false, version = "33.0.0" }
pallet-transaction-payment = { path = "../../../substrate/frame/transaction-payment", default-features = false, version = "34.0.0" }

# primitives
sp-api = { path = "../../../substrate/primitives/api", default-features = false, version = "32.0.0" }
sp-block-builder = { path = "../../../substrate/primitives/block-builder", default-features = false, version = "32.0.0" }
sp-consensus-aura = { path = "../../../substrate/primitives/consensus/aura", default-features = false, features = ["serde"], version = "0.38.0" }
sp-consensus-grandpa = { path = "../../../substrate/primitives/consensus/grandpa", default-features = false, features = ["serde"], version = "19.0.0" }
sp-core = { path = "../../../substrate/primitives/core", default-features = false, features = ["serde"], version = "33.0.1" }
sp-inherents = { path = "../../../substrate/primitives/inherents", default-features = false, version = "32.0.0" }
sp-offchain = { path = "../../../substrate/primitives/offchain", default-features = false, version = "32.0.0" }
sp-runtime = { path = "../../../substrate/primitives/runtime", default-features = false, features = ["serde"], version = "37.0.0" }
sp-session = { path = "../../../substrate/primitives/session", default-features = false, version = "33.0.0" }
sp-std = { path = "../../../substrate/primitives/std", default-features = false, version = "14.0.0" }
sp-storage = { path = "../../../substrate/primitives/storage", default-features = false, version = "21.0.0" }
sp-transaction-pool = { path = "../../../substrate/primitives/transaction-pool", default-features = false, version = "32.0.0" }
sp-version = { path = "../../../substrate/primitives/version", default-features = false, features = ["serde"], version = "35.0.0" }
sp-genesis-builder = { path = "../../../substrate/primitives/genesis-builder", default-features = false, version = "0.13.0" }

# RPC related
frame-system-rpc-runtime-api = { path = "../../../substrate/frame/system/rpc/runtime-api", default-features = false, version = "32.0.0" }
pallet-transaction-payment-rpc-runtime-api = { path = "../../../substrate/frame/transaction-payment/rpc/runtime-api", default-features = false, version = "34.0.0" }

# Used for runtime benchmarking
frame-benchmarking = { path = "../../../substrate/frame/benchmarking", default-features = false, optional = true, version = "34.0.0" }
frame-system-benchmarking = { path = "../../../substrate/frame/system/benchmarking", default-features = false, optional = true, version = "34.0.0" }

# The pallet in this template.
pallet-template = { path = "../pallets/template", default-features = false, version = "0.1.0" }

[build-dependencies]
substrate-wasm-builder = { path = "../../../substrate/utils/wasm-builder", optional = true, version = "22.0.0" }

[features]
default = ["std"]
std = [
	"codec/std",
	"scale-info/std",

	"frame-executive/std",
	"frame-support/std",
	"frame-system-benchmarking?/std",
	"frame-system-rpc-runtime-api/std",
	"frame-system/std",

	"frame-benchmarking?/std",
	"frame-try-runtime?/std",

	"pallet-aura/std",
	"pallet-balances/std",
	"pallet-grandpa/std",
	"pallet-sudo/std",
	"pallet-template/std",
	"pallet-timestamp/std",
	"pallet-transaction-payment-rpc-runtime-api/std",
	"pallet-transaction-payment/std",

	"sp-api/std",
	"sp-block-builder/std",
	"sp-consensus-aura/std",
	"sp-consensus-grandpa/std",
	"sp-core/std",
	"sp-genesis-builder/std",
	"sp-inherents/std",
	"sp-offchain/std",
	"sp-runtime/std",
	"sp-session/std",
	"sp-std/std",
	"sp-storage/std",
	"sp-transaction-pool/std",
	"sp-version/std",

	"substrate-wasm-builder",
]

runtime-benchmarks = [
	"frame-benchmarking/runtime-benchmarks",
	"frame-support/runtime-benchmarks",
	"frame-system-benchmarking/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"pallet-balances/runtime-benchmarks",
	"pallet-grandpa/runtime-benchmarks",
	"pallet-sudo/runtime-benchmarks",
	"pallet-template/runtime-benchmarks",
	"pallet-timestamp/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
]

try-runtime = [
	"frame-executive/try-runtime",
	"frame-support/try-runtime",
	"frame-system/try-runtime",
	"frame-try-runtime/try-runtime",
	"pallet-aura/try-runtime",
	"pallet-balances/try-runtime",
	"pallet-grandpa/try-runtime",
	"pallet-sudo/try-runtime",
	"pallet-template/try-runtime",
	"pallet-timestamp/try-runtime",
	"pallet-transaction-payment/try-runtime",
	"sp-runtime/try-runtime",
]
