name: Check the getting-started.sh script

on:
  push:
    branches:
      - rzadp/getting-started
  merge_group:

jobs:
  check-getting-started:
    strategy:
      matrix:
        container: [ubuntu, debian]
    runs-on: ubuntu-latest
    container: ${{ matrix.container }}:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install prerequisites
        run: |
          sudo apt update
          sudo apt install -y expect
      - name: Check the script
        run: |
          [[ "${{ runner.debug }}" == "1" ]] && FLAGS="-d" || FLAGS=""

          expect $FLAGS -c "
            spawn bash scripts/getting-started.sh

            expect {
              timeout {exit 1}
              "Detected ${{ matrix.container }}"
            }

            expect {
              timeout {exit 1}
              eof
            }
          "
        timeout-minutes: 1
