name: Check the getting-started.sh script

on:
  push:
    branches:
      - rzadp/getting-started
  merge_group:

jobs:
  check-getting-started:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install prerequisites
        run: |
          sudo apt update
          sudo apt install -y expect
      - name: Check the script
        run: |
          [[ "${{ runner.debug }}" == "1" ]] && FLAGS="-d" || FLAGS=""

          expect $FLAGS << EOF
            spawn bash scripts/getting-started.sh

            expect {
              timeout {exit 1}
              -exact "Detected Debian"
            }

            expect {
              timeout {exit 1}
              -exact "Detected Ubuntu"
            }

            expect {
              timeout {exit 1}
              eof
            }

          EOF
        timeout-minutes: 1
