name: Check the getting-started.sh script

on:
  push:
    branches:
      - rzadp/getting-started
  merge_group:

jobs:
  check-getting-started:
    strategy:
      fail-fast: false
      matrix:
        container: [ubuntu, debian]
    runs-on: ubuntu-latest
    container: ${{ matrix.container }}:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install prerequisites
        run: apt update && apt install -y expect
      - name: Check the script
        run: |
          [[ "${{ runner.debug }}" == "1" ]] && FLAGS="-d" || FLAGS=""

          expect $FLAGS -c '
          expect_before {
            timeout { puts stderr "Timed out on an expect"; exit 1 }
            eof { puts stderr "EOF received on an expect"; exit 1 }
          }

          spawn bash scripts/getting-started.sh

          expect "Detected ${{ matrix.container }}"

          expect {
            timeout {exit 1}
            eof
          }
          '
        shell: bash
        timeout-minutes: 1
