name: Check the getting-started.sh script

on:
  push:
    branches:
      - rzadp/getting-started
  merge_group:

jobs:
  check-getting-started:
    strategy:
      fail-fast: false
      matrix:
        container: [ubuntu, debian]
    runs-on: ubuntu-latest
    container: ${{ matrix.container }}:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install prerequisites
        run: apt update && apt install -y expect sudo
      - run: bash scripts/getting-started.sh
      - name: Check the script
        run: |
          # Add a debug flag to expect, if github is re-run with debug logging enabled.
          [[ "${{ runner.debug }}" == "1" ]] && FLAGS="-d" || FLAGS=""

          expect $FLAGS -c '
          expect_before {
            timeout { puts stderr "Timed out on an expect"; exit 1 }
            eof { puts stderr "EOF received on an expect"; exit 1 }
          }

          spawn bash scripts/getting-started.sh

          expect "Detected ${{ matrix.container }}"

          expect -exact "Setup the Rust environment"
          send "y\r"

          expect -exact "start with one of the templates"
          send "n\r"

          expect eof
          '
        shell: bash
        timeout-minutes: 1
