name: Command-Action

on:
  pull_request:
  issue_comment:
    types: [created]

jobs:
  cmd-check:
    runs-on: ubuntu-latest
    name: Bot
    steps:
      - uses: actions/checkout@v4
      - run: gh pr checkout ${{ github.event.issue.number || github.event.pull_request.number }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - uses: paritytech/cmd-action@parse-comment
        id: cmd
        with:
          commands-directory: ".github/commands"
          GITHUB_TOKEN: ${{ github.token }}
      - name: Print commands
        run: echo "Commands are $CMD"
        env:
          CMD: ${{ steps.cmd.outputs.commands }}
