name: Command-Action

on:
  pull_request:
  issue_comment:
    types: [created]

jobs:
  cmd-check:
    runs-on: ubuntu-latest
    name: Bot
    steps:
      - uses: actions/checkout@v4
      - uses: paritytech/cmd-action@parse-comment
        id: cmd
        with:
          commands-directory: ".github/scripts"
          GITHUB_TOKEN: ${{ github.token }}
      - name: Print commands
        run: "Commands are $CMD"
        env:
          CMD: ${{ steps.cmd.outputs.commands }}
