name: Publish templates


on:
  push:


jobs:
  publish-templates:
    runs-on: ubuntu-latest
    container:
      image: docker.io/paritytech/ci-unified:bullseye-1.75.0-2024-01-22-v20240109
    strategy:
      matrix:
        template: ["minimal"]
    env:
      template-path: "polkadot-sdk-${{ matrix.template }}-template"
      polkadot-release-version: "1.8.0"
    steps:
      - name: Configure git identity
        run: |
          git config --global user.name "Template Bot"
          git config --global user.email "163130811+polkadot-sdk-template-bot-stg[bot]@users.noreply.github.com"
      - uses: actions/checkout@v3
        with:
          path: polkadot-sdk
      - name: Generate token
        id: app_token
        uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a # v2.1.0
        with:
          app_id: ${{ secrets.TEMPLATE_APP_ID }}
          private_key: ${{ secrets.TEMPLATE_APP_KEY }}
      - uses: actions/checkout@v3
        with:
          repository: "paritytech-stg/polkadot-sdk-${{ matrix.template }}-template"
          path: "${{ env.template-path }}"
          token: ${{ steps.app_token.outputs.token }}
      - name: Install Polkadot SDK Version Manager
        run: cargo install --git https://github.com/paritytech/psvm --rev 3ed634e47c595ce9912e4645d71ae2c527dc72a7 psvm
      - name: Replace the workspace references in the template
        run: |
          set -euo pipefail
          # Use released creates, instead of git references.
          find . -type f -name 'Cargo.toml' -exec psvm -o -v ${{ env.polkadot-release-version }} -p {} \;

          # frame/polkadot-sdk-frame is not a part of release yet, treat it manually.
          find . -type f -name 'Cargo.toml' -exec sed -i -E "s/package = \"frame\", path = .*\/substrate\/frame\", //g" {} \;
          
          # Set the Rust edition.
          rust_edition=$(cat ../../Cargo.toml | grep "edition =")
          find . -type f -name 'Cargo.toml' -exec sed -i -E "s/edition\.workspace = true\$/$rust_edition/g" {} \;

          # Get rid of "authors.workspace = true" and similar entries.
          find . -type f -name 'Cargo.toml' -exec sed -i -E "s/^.*\.workspace = true\$//g" {} \;
          find . -type f -name 'Cargo.toml' -exec sed -i -E "s/^workspace = true\$//g" {} \;

          # Replace workspace dependencies with actual versions.
          # e.g. serde_json = { workspace = true, default-features = true }
          replace_workspace_deps () {
            # To preserve TAB identation.
            IFS=''
            echo "Replacing workspace deps in $1"
            while read line; do
              if echo "$line" | grep -q -E ".* = .* workspace = true"
              then
                pkg=$(echo $line | sed -E 's/(.*) = \{(.*)/\1/')
                echo "Replacing workspace dependency ${pkg}."
                cargo tree --depth 1 --prefix none | grep "${pkg} v"
                version=$(cargo tree --depth 1 --prefix none | grep "${pkg} v" | head -1 | sed -E "s/${pkg} v//" | tr -d '\n')
                echo "Version: $version"
                line=$(echo "$line" | sed -E "s/workspace = true/version = \"${version}\"/")
              fi
              echo "$line" >> "${1}.temp"
            done < "$1"
            mv "${1}.temp" "$1"
          }
          export -f replace_workspace_deps
          find . -type f -name 'Cargo.toml' -exec bash -c 'replace_workspace_deps {}' \;

          echo "Result Cargo.toml debug"
          find . -type f -name 'Cargo.toml' -exec cat {} \;
        shell: bash
        working-directory: polkadot-sdk/templates/${{ matrix.template }}/
      - name: Clean the destination repository
        run: rm -rf "${{ env.template-path }}/*"
      - name: Copy over the new changes
        run: |
          cp -r polkadot-sdk/templates/${{ matrix.template }}/* "${{ env.template-path }}/"
      - name: Check if it compiles
        id: check-compilation
        run: |
          set -e
          cd node
          # Commented out for now because it's very long.
          # cargo build
          cargo tree --depth 1
        working-directory: "${{ env.template-path }}"
      - name: Push changes
        run: |
          git add -A
          git commit --allow-empty -m "Pushed event"
          git push
        working-directory: "${{ env.template-path }}"
