name: Review-Trigger

on:
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize
      - review_requested
      - review_request_removed
      - ready_for_review
  pull_request_review:
  merge_group:

jobs:
  trigger-review-bot:
    # (It is not a draft) && (it is not a review || it is an approving review)
    if: ${{ github.event.pull_request.draft != true && (github.event_name != 'pull_request_review' || (github.event.review && github.event.review.state == 'APPROVED')) }}
    runs-on: ubuntu-latest
    name: trigger review bot
    steps:
      - name: Get PR number
        if: ${{ github.event_name != 'merge_group' }}
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          echo "Saving PR number: $PR_NUMBER"
          mkdir -p ./pr
          echo $PR_NUMBER > ./pr/pr_number
      - uses: actions/upload-artifact@v3
        if: ${{ github.event_name != 'merge_group' }}
        name: Save PR number
        with:
          name: pr_number
          path: pr/
          retention-days: 5
      - name: Generate token
        if: ${{ github.event_name == 'merge_group' }}
        id: app_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.REVIEW_APP_ID }}
          private_key: ${{ secrets.REVIEW_APP_KEY }} 
      - run: echo "Running with commit $ID"
        env:
          ID: ${{ github.event.merge_group.head_commit.id }}
      - name: Add Merge Queue status check
        if: ${{ github.event_name == 'merge_group' }}
        uses: billyjbryant/create-status-check@v2
        with:
          authToken: ${{ steps.app_token.outputs.token }}
          context: 'Approved Merge Queue'
          description: 'PRs for merge queue gets approved'
          state: 'success'
          sha: ${{ github.event.merge_group.head_commit.id || github.sha}}
