# GHA for test-linux-stable-int, test-linux-stable, test-linux-stable-oldkernel
name: tests linux stable

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  merge_group:
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  preflight:
    uses: ./.github/workflows/reusable-preflight.yml

  #
  #
  #
  test-linux-stable-archive:
    needs: [preflight]
    runs-on: ${{ needs.preflight.outputs.RUNNER }}
    timeout-minutes: 60
    container:
      image: ${{ needs.preflight.outputs.IMAGE }}
      # needed for tests that use unshare syscall
      options: --security-opt seccomp=unconfined
    env:
      RUST_TOOLCHAIN: stable
      # Enable debug assertions since we are running optimized builds for testing
      # but still want to have debug assertions.
      RUSTFLAGS: "-Cdebug-assertions=y -Dwarnings"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: script
        id: required
        run: |
          # Fixes "detected dubious ownership" error in the ci
          git config --global --add safe.directory '*'
          forklift cargo nextest archive --archive-file test-linux-stable-nextest-build.tar.zst \
            --workspace \
            --locked \
            --release \
            --cargo-quiet \
            --features try-runtime,experimental,ci-only-tests

      - run: ls -al

      - uses: actions/upload-artifact@v4
        with:
          name: test-linux-stable-nextest-build.tar.zst
          path: test-linux-stable-nextest-build.tar.zst

  test-linux-stable:
    needs: [preflight, test-linux-stable-archive]
    runs-on: ${{ matrix.runners }}
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        partition: [1/3, 2/3, 3/3]
        runners:
          [
            "${{ needs.preflight.outputs.RUNNER }}",
          ]
    container:
      image: ${{ needs.preflight.outputs.IMAGE }}
      # needed for tests that use unshare syscall
      options: --security-opt seccomp=unconfined
    env:
      RUST_TOOLCHAIN: stable
      # Enable debug assertions since we are running optimized builds for testing
      # but still want to have debug assertions.
      RUSTFLAGS: "-Cdebug-assertions=y -Dwarnings"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: test-linux-stable-nextest-build.tar.zst

      - name: script
        id: required
        run: |
          # Fixes "detected dubious ownership" error in the ci
          git config --global --add safe.directory '*'
          cargo nextest run \
            --archive-file test-linux-stable-nextest-build.tar.zst \
            --no-fail-fast \
            --partition count:${{ matrix.partition }}